version: 0.2

env:
  variables:
    NODE_ENV: production

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies
      - corepack enable
      - yarn install --immutable

  build:
    commands:
      - echo Running Next.js build
      - yarn build
      - test -d out || exit 1
      - echo Static export completed

  post_build:
    commands:
      - echo Deploying to S3
      - aws s3 sync out s3://$S3_BUCKET --delete
      - aws s3 cp out/index.html s3://$S3_BUCKET/index.html --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html
      - echo Invalidating CloudFront
      - aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"

artifacts:
  files:
    - "**/*"
